name: Veracode Upload and Scan
on:
  # Run once monthly
  schedule:
    - cron: '0 0 1 */1 *'

  # Allow manual runs to be triggered
  workflow_dispatch:

jobs:
  static_analysis:
    uses: seismic/github-actions/.github/workflows/veracode.yml@master
    secrets: inherit
    with:
      javascript: true
